FROM node:24-slim

ARG CONTAINER_USER
ARG CONTAINER_USER_HOME
ARG CONTAINER_ROOT
ARG USER_UID
ARG USER_GID=$USER_UID

RUN \
  apt-get update \ 
  && apt-get upgrade -y \
  && apt-get install -y --no-install-recommends \
  sudo \
  git \
  ca-certificates \
  vim \
  curl \
  procps \ 
  fontconfig \ 
  wget \
  unzip

RUN set -eux; \
  # ホストのUID/GIDを引き渡す場合、OS上に既にUID/GIDが存在してもエラーが発生しないようにする為の削除処理
  if getent passwd "${USER_UID}" >/dev/null; then \
  olduser=$(getent passwd "${USER_UID}" | cut -d: -f1); \
  echo "USER_UID ${USER_UID} already used by ${olduser}, deleting..."; \
  userdel -r -f "${olduser}" || true; \
  fi; \
  if getent group "${USER_GID}" >/dev/null; then \
  oldgroup=$(getent group "${USER_GID}" | cut -d: -f1); \
  echo "USER_GID ${USER_GID} already used by ${oldgroup}, deleting..."; \
  groupdel "${oldgroup}" || true; \
  fi

RUN set -eux; \
  # create user
  groupadd -g ${USER_GID} ${CONTAINER_USER} \
  && useradd -s /bin/zsh -u ${USER_UID} -g ${USER_GID} -m ${CONTAINER_USER} \
  # sudo setting
  && echo ${CONTAINER_USER} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${CONTAINER_USER} \
  && chmod 0440 /etc/sudoers.d/${CONTAINER_USER}

USER ${CONTAINER_USER}
WORKDIR ${CONTAINER_ROOT}

# 先に作成しておかないと所有者がrootとなる為
RUN mkdir node_modules

# フォントファイルをコピーして展開
RUN sudo mkdir -p /usr/local/share/fonts
RUN sudo wget -O /usr/local/share/fonts/HackGen_v2.10.0.zip https://github.com/yuru7/HackGen/releases/download/v2.10.0/HackGen_v2.10.0.zip \
  && sudo unzip /usr/local/share/fonts/HackGen_v2.10.0.zip -d /usr/local/share/fonts/ \
  && sudo rm /usr/local/share/fonts/HackGen_v2.10.0.zip

# フォントキャッシュを更新
RUN fc-cache -f -v